### ISSUE TITLE
Incompatible with WebComponentExporter

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/skeleton-starter-flow-spring#176]
Vaadin 14 beta3. 

`java.lang.IllegalArgumentException: Supplied writer 'com.vaadin.flow.server.webcomponent.WebComponentModulesWriter' and supplied exporter 'com.example.app.spring.GridDemoExporter' have different class loaders, 'jdk.internal.loader.ClassLoaders$AppClassLoader' and 'org.springframework.boot.devtools.restart.classloader.RestartClassLoader', respectively. Writer and exporters must share a class loader.
`

**Comment by denis-anisimov** [comment]
Could you please provide steps to reproduce this ?

**Comment by denis-anisimov** [comment]
Are you sure by the way that this is a bug for the starter spring project ?
I see `com.example.app.spring.GridDemoExporter` which is not known class and most likely a custom class.
Which means this is an "issue" in Flow.

**Comment by marcushellberg** [comment]
If you look at the end of the trace, I think the issue is that the starter uses Spring Boot DevTools, which uses a different classloader. So this is really more of a documentation bug in that sense

**Comment by denis-anisimov** [comment]
I'm not sure that this is documentation bug.

If it's a spring application which uses spring boot dev tools then it might be that we should fix something in our code.
There has been similar issue with classloader in `Instantiator` for Spring impl.
May be this is something which requires a proper classloader selection as well.

So: is it a customer report ?
Or something discovered by you ?
I still would like to see minimal example to reproduce the issue.
Otherwise we can't be sure whether we are able to reproduce the issue or not.

Just a not from my side:
- some simple starter app
- the app uses spring dev tools
- there is a web component exporter
So the app is going to be embedded.

**Comment by marcushellberg** [comment]
Here is a simple reproduction. 
1. Take starter
2. Add web component exporter
3. `mvn package spring-boot:run`
4. 💥

[export-go-boom-boom.zip](https://github.com/vaadin/skeleton-starter-flow-spring/files/3315215/export-go-boom-boom.zip)

It's something I discovered, but I don't see how that makes it any less relevant.

**Comment by denis-anisimov** [comment]
Thanks.
Now I can reproduce it.

**Comment by ujoni** [comment]
A work-around is to remove the `spring-boot-devtools` which disables the reload feature. The actual problem is with how Flow's `DefaultClassFinder` and Spring's reload feature interact. Fixing that requires some further thought.

**Comment by ujoni** [comment]
I was not able to replicate this problem after applying the patch https://github.com/vaadin/flow/pull/5972
