### ISSUE TITLE
When opening MainView <body> is empty

### ISSUE THREAD

**Issue by mkerkhoff** [vaadin/skeleton-starter-flow-spring#9]
Team, I am trying to get Spring Boot working wit Flow to understand what I need to do for porting my existing app to flow.  However I can not get my Skeleton Project to work. Can not get my head around it.

I can see it accesses the MainView nicely however the response contains an empty body it only contains <noscript>. Using the pom.xml as provided in the skeleton. Look it number of areas but can not find any clue where to look for.  

UPDATE
bootstrap js for Vaadin was not accesible. Copied it to the resource folder and then it all worked fine.

Marc.

**Comment by denis-anisimov** [comment]
It looks like something wrong with your maven artifacts.
It should work out of the box. But for some reason some jars are cached somehow and used instead of correct ones.
I would recommend to make a clean build with removing all your vaadin artifacts from your maven local repo.
You can use `clean install -U` maven arguments or  completely clean the local cache via `dependency:purge-local-repository clean install` .

**Comment by anasmi** [comment]
Closing issue. Please, let us know, if the issue will occur again under any circumstances
